### ISSUE TITLE
PatternTracker sending 0s for x, y, z

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/ColorPatternTracker#1]
I've tried writing a Java app that uses the BluetoothLibrary and the BTReceiverClass to receive position information.  Got all 0s for x, y, and z.  So, I built the PatternTracker from source so I could debug it.  The PatternTracker appears to be sending out all 0s.  I can see the pattern on the S6 and can see a number of dots displayed on the pattern (white ones near the center, red ones on the outer most edges), so I assume the tracker is seeing and recognizing the pattern.  I have it looking at pattern 0.  Here's a snippet from logcat when I grep for cgt:

D/cgt     (30625): Tracking for 0
D/cgt     (30625): patID [1.533333 0.015345] [2.522876 0.018653] [0.615686 0.554140] [2.437908 0.001609] [2.422222 0.001619] [2.367320 0.000000] [0.550327 0.748219] [2.530719 0.106921] [1.592157 0.100985] [0.571242 0.665904] [0.458824 0.008547] [0.583007 0.625561]
D/cgt     (30625): running end marking
D/cgt     (30625): running marking
D/cgt     (30625): refining finished 1
D/cgt     (30625): Finished OpenCL kernels in 22.888708 ms
D/cgt     (30625): running opencl
D/cgt     (30625): running kernels
D/cgt     (30625): copying colors
D/cgt     (30625): refining corners
D/cgt     (30625): Tracking for 0
D/cgt     (30625): patID [1.546405 0.017751] [2.516340 0.018701] [0.623529 0.534591] [2.454902 0.003195] [2.403922 0.003263] [2.375163 0.003302] [0.541176 0.760870] [2.538562 0.106591] [1.593464 0.098441] [0.580392 0.648649] [0.475817 0.016484] [0.579085 0.629797]

And here's a snippet from logcat when I grep for Track:
D/cgt     (30625): Tracking for 0
I/2Track  (30625): Time: calibrate points: 0.173792 ms
I/2Track  (30625): Time: RTsFromCorres: 2.467792 ms
I/2Track  (30625): Time: populate Rel Transf: 0.089667 ms
E/Track   (30625): x:0.0 y:0.0 z:0.0
I/2Track  (30625): Time: predict corners: 0.1495 ms
D/cgt     (30625): Tracking for 0

Any idea on what step I missed?  or something else I'm missing?

**Comment by nagarabh** [comment]
Thanks Thomas for pointing this out. Please check the update and let me know if all is ok now.

**Comment by thomasflynn** [comment]
ok, updated, got things to compile again (i'm on linux :), still getting 0s:

D/cgt     (21682): Tracking for 0
I/2Track  (21682): Time: calibrate points: 0.161375 ms
I/2Track  (21682): Time: RTsFromCorres: 2.824833 ms
I/2Track  (21682): Time: populate Rel Transf: 0.093833 ms
E/Track   (21682): x:0.0 y:0.0 z:0.0

**Comment by thomasflynn** [comment]
btw, i think i'll do a quick pull-request with the changes i needed to compile on linux.

**Comment by nagarabh** [comment]
Please see the updated compilation instructions in Readme.md. Hope it is convenient. I would like to avoid using OPENCV_HOME variable as I may have multiple versions of opencv. Regarding zeros in "Track" try to avoid using breakpoints and let it run while viewing the pattern 0 for more than one frame.

**Comment by thomasflynn** [comment]
re: OPENCV  how about a path relative to where ColorPatternTracker is checked out?

re: Tracker, i didn't set any breakpoints or even use a debugger.  I just launched it and grepped the output from adb.  This week has been real busy, so i havent had a chance to dig in further :(

**Comment by thomasflynn** [comment]
ok, i finally got non-zero values.  i had both the phone and pattern 0 on stands.  after i had pattern 0 on the stand, then put another pattern, then put pattern 0 back, I got non-zero values.  it seems like it needs to at least briefly detect another pattern before it starts working.

**Comment by nagarabh** [comment]
Please check the latest version I just uploaded. The issue seems to be resolved now. I yesterday just checked on github page where all the patterns are present so was missing the issue :(

**Comment by thomasflynn** [comment]
yeah, seems to be working better now.  Thanks!
